<?php
// +---------------------------------------------------------------------------+
// | CAPTCHA for glFusion CMS                                                  |
// +---------------------------------------------------------------------------+
// | CAPTCHA Static Image Set                                                  |
// +---------------------------------------------------------------------------+
// | Copyright (C) 2006-2017 by the following authors:                         |
// |                                                                           |
// | Adapted for glFusion CMS by: Mark R. Evans <mark AT glfusion DOT org>     |
// +---------------------------------------------------------------------------+
// |                                                                           |
// | This program is free software; you can redistribute it and/or             |
// | modify it under the terms of the GNU General Public License               |
// | as published by the Free Software Foundation; either version 2            |
// | of the License, or (at your option) any later version.                    |
// |                                                                           |
// | This program is distributed in the hope that it will be useful,           |
// | but WITHOUT ANY WARRANTY; without even the implied warranty of            |
// | MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the             |
// | GNU General Public License for more details.                              |
// |                                                                           |
// | You should have received a copy of the GNU General Public License         |
// | along with this program; if not, write to the Free Software Foundation,   |
// | Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.           |
// |                                                                           |
// +---------------------------------------------------------------------------+
//
// this file can't be used on its own
if (!defined ('GVERSION')) {
    die ('This file can not be used on its own.');
}
global $staticimageset, $cString, $cCount;
$staticimageset = array();
$staticimageset['name'] = 'Default';
$cCount = 103;
$cString = array('0EYP0S','1F770D','28XOYI','2LDUMD','47TXJC','4ITVAP','4JKOGQ','5E66T1','5LSG1C','6URYYP','7G1AG0','7GZY5S','7Q2WOZ','7SMW7J','83EY3L','8C99ZZ','8MNIAX','8N91KL','8NFLWQ','8RL5MD','9KR3EJ','BI1ZCZ','BPHOX9','BRWLVK','BZTIGV','C0HK4F','C2QOUK','CFE1YM','CJANGI','CQY9FX','CXUH5S','CYO0Y1','DHGFOZ','DQFRUI','DUZCN2','E5SZ52','ECGLOZ','EE37I4','ELWSDN','F6A0KP','F7VU1K','FZAL8O','G5DCR5','G9J7VC','GBHHGT','GFACI5','GP6LL9','GXIRNW','H5FLY1','HH0NAF','HWYMU6','I0VFY9','I0W79K','I121OQ','I1AZAU','I7CQIR','IIOGVW','IKF3O4','IKJM7C','INNH12','IO0H0L','IWXXTN','J7XDFF','JF4UH8','JSMSI9','K1LUBX','K55DZL','KIFH52','KVKZU2','L3QMM1','LRW7O3','MFWUDW','ML976T','N1KL1P','O3UV7A','OB87BK','ODH566','OE8PKO','OOHUIW','PSWO3K','PZ4CS0','Q1PAGZ','R8OVM4','RAKUHA','SK908O','TDGQSM','TG3ZTE','U4IG9B','U5R7PW','UJ97BE','VANJZK','VN6QKH','VPLW5R','VTZDK1','VUYFUH','WJDUK2','WP0QYS','XDIYL2','XUKG66','YE9U9N','YQ73D3','YTWL2C','ZNF56M','ZYO016');
?>