<?php
  /* Contributed by: Walter Rowe (www.WalterRowePhotography.com) */
$frameData = array(

'name' => 'Halo',

/* Top Left */
'imageTL' => 'TL.png',
'widthTL' => 13,
'heightTL' => 13,

/* Top */
'imageTTL' => '',
'widthTTL' => 0,

'imageTT' => 'TC.png',
'heightTT' => 13,

'imageTTR' => '',
'widthTTR' => 0,

/* Top Right */
'imageTR' => 'TR.png',
'widthTR' => 13,
'heightTR' => 13,

/* Left */
'imageLLT' => '',
'heightLLT' => 0,

'imageLL' => 'LC.png',
'widthLL' => 13,

'imageLLB' => '',
'heightLLB' => 0,

/* Right */
'imageRRT' => '',
'heightRRT' => 0,

'imageRR' => 'RC.png',
'widthRR' => 13,

'imageRRB' => '',
'heightRRB' => 0,

/* Bottom Left */
'imageBL' => 'BL.png',
'widthBL' => 13,
'heightBL' => 13,

/* Bottom */
'imageBBL' => '',
'widthBBL' => 0,

'imageBB' => 'BC.png',
'heightBB' => 13,

'imageBBR' => '',
'widthBBR' => 0,

/* Bottom Right */
'imageBR' => 'BR.png',
'widthBR' => 13,
'heightBR' => 13

);
?>
