<?php
  /* Contributed by: floridave */
$frameData = array(

'name' => 'Shells',

/* Top Left */
'imageTL' => 'TL.jpg',
'widthTL' => 58,
'heightTL' => 58,

/* Top */
'imageTTL' => '',
'widthTTL' => 0,

'imageTT' => 'TT.jpg',
'heightTT' => 58,

'imageTTR' => '',
'widthTTR' => 0,

/* Top Right */
'imageTR' => 'TR.jpg',
'widthTR' => 58,
'heightTR' => 58,

/* Left */
'imageLLT' => '',
'heightLLT' => 0,

'imageLL' => 'LL.jpg',
'widthLL' => 58,

'imageLLB' => '',
'heightLLB' => 0,

/* Right */
'imageRRT' => '',
'heightRRT' => 0,

'imageRR' => 'RR.jpg',
'widthRR' => 58,

'imageRRB' => '',
'heightRRB' => 0,

/* Bottom Left */
'imageBL' => 'BL.jpg',
'widthBL' => 58,
'heightBL' => 58,

/* Bottom */
'imageBBL' => '',
'widthBBL' => 0,

'imageBB' => 'BB.jpg',
'heightBB' => 58,

'imageBBR' => '',
'widthBBR' => 0,

/* Bottom Right */
'imageBR' => 'BR.jpg',
'widthBR' => 58,
'heightBR' => 58

);
?>
