<?php
$frameData = array(

'name' => 'Postage Stamp',

/* TTL */
'imageTTL' => 'TT5.gif',
'widthTTL' => 10,
'heightTTL' => 10,

/* TTR */
'imageTTR' => 'TT5.gif',
'widthTTR' => 10,
'heightTTR' => 10,

/* LLT */
'imageLLT' => 'LL5.gif',
'widthLLT' => 10,
'heightLLT' => 10,

/* RRT */
'imageRRT' => "RR5.gif",
'widthRRT' => 10,
'heightRRT' => 10,

/* LLB */
'imageLLB' => "LL5.gif",
'widthLLB' => 10,
'heightLLB' => 10,

/* RRB */
'imageRRB' => "RR5.gif",
'widthRRB' => 10,
'heightRRB' => 10,

/* BBL */
'imageBBL' => "BB5.gif",
'widthBBL' => 10,
'heightBBL' => 10,

/* BBR */
'imageBBR' => "BB5.gif",
'widthBBR' => 10,
'heightBBR' => 10,

/* TL Top left */
'imageTL' => "TL5.gif",
'widthTL'=>10,
'heightTL'=>10,

/* TT Top */
'imageTT' => "TT5.gif",
'widthTT' => 10,
'heightTT' => 10,

/* TR Top right */
'imageTR' => "TR5.gif",
'widthTR'=>10,
'heightTR'=>10,

/* LL Left side */
'imageLL' => "LL5.gif",
'widthLL' => 10,
'heightLL' => 10,

/* RR Right side */
'imageRR' => "RR5.gif",
'widthRR' => 10,
'heightRR' => 10,

/* BL Bottom left */
'imageBL' => "BL5.gif",
'heightBL'=>10,
'widthBL'=>10,

/* BB Bottom */
'imageBB' => "BB5.gif",
'widthBB' => 10,
'heightBB' => 10,

/* BR Bottom Right */
'imageBR' => "BR5.gif",
'widthBR'=>10,
'heightBR'=>10

);
?>