<?php
$frameData = array(

'name' => 'Kodak',

/* Top Left */
'imageTL' => 'TL.gif',
'widthTL' => 0,
'heightTL' => 0,

/* Top */
'imageTTL' => 'TTL.gif',
'widthTTL' => 89,
'heightTTL' => 20,

'imageTT' => 'TT.gif',
'widthTT' => 19,
'heightTT' => 20,

'imageTTR' => 'TTR.gif',
'widthTTR' => 42,
'heightTTR' => 20,

/* Top Right */
'imageTR' => 'TR.gif',
'widthTR' => 0,
'heightTR' => 0,

/* Left */
'imageLLT' => 'LLT.gif',
'widthLLT' => 0,
'heightLLT' => 0,

'imageLL' => 'LL.gif',
'heightLL' => 0,
'widthLL' => 0,

'imageLLB' => 'LLB.gif',
'widthLLB' => 0,
'heightLLB' => 0,


/* Right */
'imageRRT' => 'RRT',
'widthRRT' => 0,
'heightRRT' => 0,


'imageRR' => 'RR.gif',
'widthRR' => 0,
'heightRR' => 0,

'imageRRB' => 'RRB.gif',
'widthRRB' => 0,
'heightRRB' => 0,

/* Bottom Left */
'imageBL' => 'BL.gif',
'widthBL' => 0,
'heightBL' => 0,

/* Bottom */
'imageBBL' => 'BBL.gif',
'widthBBL' => 89,
'heightBBL' => 23,

'imageBB' => 'BB.gif',
'widthBB' => 19,
'heightBB' => 23,

'imageBBR' => 'BBR.gif',
'widthBBR' => 42,
'heightBBR' => 23,

/* Bottom Right */
'imageBR' => 'BR.gif',
'widthBR' => 0,
'heightBR' => 0

);
?>
