<?php
// +--------------------------------------------------------------------------+
// | glFusion CMS                                                             |
// +--------------------------------------------------------------------------+
// | deleted.php                                                              |
// |                                                                          |
// | glFusion Installation                                                    |
// +--------------------------------------------------------------------------+
// | Copyright (C) 2015-2016 by the following authors:                        |
// |                                                                          |
// | Mark R. Evans          mark AT glfusion DOT org                          |
// +--------------------------------------------------------------------------+
// |                                                                          |
// | This program is free software; you can redistribute it and/or            |
// | modify it under the terms of the GNU General Public License              |
// | as published by the Free Software Foundation; either version 2           |
// | of the License, or (at your option) any later version.                   |
// |                                                                          |
// | This program is distributed in the hope that it will be useful,          |
// | but WITHOUT ANY WARRANTY; without even the implied warranty of           |
// | MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            |
// | GNU General Public License for more details.                             |
// |                                                                          |
// | You should have received a copy of the GNU General Public License        |
// | along with this program; if not, write to the Free Software Foundation,  |
// | Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.          |
// |                                                                          |
// +--------------------------------------------------------------------------+

if (!defined ('GVERSION')) {
    die ('This file can not be used on its own!');
}

$obsoletePrivateDir = array(
    'system/classes/openid/',
    'system/pear/Auth/',
    'system/pear/Console/',
    'system/pear/scripts/',
    'system/pear/Services/',

);

$obsoletePublicDir = array(
    'ckeditor/plugins/filemanager/',
);

$obsoletePrivateFiles = array(
    'lib/getid3/dependencies.txt',
    'lib/getid3/readme.txt',
    'lib/getid3/structure.txt',
    'sql/updates/geeklog_mysql_1.4.1_to_1.5.0.php',

    'system/pear/Date.php',
    'system/pear/pearcmd.php',
    'system/pear/peclcmd.php',

    'plugins/spamx/BaseAdmin.class.php',
    'plugins/spamx/BaseCommand.class.php',
    'plugins/spamx/BlackList.Examine.class.php',
    'plugins/spamx/DeleteComment.Action.class.php',
    'plugins/spamx/EditBlackList.Admin.class.php',
    'plugins/spamx/EditHeader.Admin.class.php',
    'plugins/spamx/EditIP.Admin.class.php',
    'plugins/spamx/EditIPofURL.Admin.class.php',
    'plugins/spamx/Header.Examine.class.php',
    'plugins/spamx/IP.Examine.class.php',
    'plugins/spamx/IPofUrl.Examine.class.php',
    'plugins/spamx/MailAdmin.Action.class.php',
    'plugins/spamx/MassDelete.Admin.class.php',
    'plugins/spamx/MassDelTrackback.Admin.class.php',
    'plugins/spamx/SFS.Examine.class.php',
    'plugins/spamx/SFS.Misc.class.php',
    'plugins/spamx/SFSbase.class.php',
    'plugins/spamx/SFSreport.Action.class.php',
    'plugins/spamx/SLV.Examine.class.php',
    'plugins/spamx/SLVbase.class.php',
    'plugins/spamx/SLVreport.Action.class.php',
    'plugins/spamx/SLVwhitelist.Admin.class.php',
    'plugins/spamx/modules/SLV.Examine.class.php',
    'plugins/spamx/modules/SLVbase.class.php',
    'plugins/spamx/modules/SLVreport.Action.class.php',
    'plugins/spamx/modules/SLVwhitelist.Admin.class.php',

    'plugins/spamx/modules/SFSreport.Action.class.php',

    'system/classes/openidhelper.class.php',

);

$obsoletePublicFiles = array(
    'admin/install/help.php',
    'admin/install/layout/arrow-back.gif',
    'admin/install/layout/arrow-next.gif',
    'admin/install/layout/arrow-recheck.gif',
    'admin/install/layout/arrow.png',
    'admin/install/layout/arrow_down.png',
    'admin/install/layout/arrow_open.png',
    'admin/install/layout/bottom-l-corner.png',
    'admin/install/layout/bottom-r-corner.png',
    'admin/install/layout/check.png',
    'admin/install/layout/error.png',
    'admin/install/layout/gl_moomenu1-bg.gif',
    'admin/install/layout/gl_moopngfix.js',
    'admin/install/layout/header-bg.png',
    'admin/install/layout/ie6.css',
    'admin/install/layout/ie7.css',
    'admin/install/layout/mootools-release-1.11.packed.js',
    'admin/install/layout/steplist-bottom.png',
    'admin/install/layout/steplist-repeat.png',
    'admin/install/layout/top-l-corner.png',
    'admin/install/layout/top-r-corner.png',
    'admin/install/layout/top.png',
    'admin/install/toinnodb.php',
    'docs/docstyle.css',
    'docs/images/background.gif',
    'docs/images/index.html',
    'layout/cms/plugins/bad_behavior2/ban_entry.thtml',
    'layout/cms/plugins/bad_behavior2/index.html',
    'layout/cms/plugins/bad_behavior2/log.thtml',
    'layout/cms/plugins/calendar/addevent.thtml',
    'layout/cms/plugins/calendar/addeventoption.thtml',
    'layout/cms/plugins/calendar/admin/batchadmin.thtml',
    'layout/cms/plugins/calendar/admin/eventeditor.thtml',
    'layout/cms/plugins/calendar/admin/index.html',
    'layout/cms/plugins/calendar/calendar.thtml',
    'layout/cms/plugins/calendar/calendarevent.thtml',
    'layout/cms/plugins/calendar/dayview/column.thtml',
    'layout/cms/plugins/calendar/dayview/dayview.thtml',
    'layout/cms/plugins/calendar/dayview/index.html',
    'layout/cms/plugins/calendar/dayview/quickaddform.thtml',
    'layout/cms/plugins/calendar/editpersonalevent.thtml',
    'layout/cms/plugins/calendar/eventdetails.thtml',
    'layout/cms/plugins/calendar/events.thtml',
    'layout/cms/plugins/calendar/index.html',
    'layout/cms/plugins/calendar/mastercalendaroption.thtml',
    'layout/cms/plugins/calendar/personalcalendaroption.thtml',
    'layout/cms/plugins/calendar/submitevent.thtml',
    'layout/cms/plugins/calendar/weekview/custom/index.html',
    'layout/cms/plugins/calendar/weekview/events.thtml',
    'layout/cms/plugins/calendar/weekview/index.html',
    'layout/cms/plugins/calendar/weekview/weekview.thtml',
    'layout/cms/plugins/captcha/captcha.thtml',
    'layout/cms/plugins/captcha/captcha_calendar.thtml',
    'layout/cms/plugins/captcha/captcha_comment.thtml',
    'layout/cms/plugins/captcha/captcha_contact.thtml',
    'layout/cms/plugins/captcha/captcha_emailstory.thtml',
    'layout/cms/plugins/captcha/captcha_forum.thtml',
    'layout/cms/plugins/captcha/captcha_links.thtml',
    'layout/cms/plugins/captcha/captcha_registration.thtml',
    'layout/cms/plugins/captcha/captcha_story.thtml',
    'layout/cms/plugins/captcha/captcha_token.thtml',
    'layout/cms/plugins/captcha/index.html',
    'layout/cms/plugins/ckeditor/ckeditor.thtml',
    'layout/cms/plugins/ckeditor/ckeditor_block.thtml',
    'layout/cms/plugins/ckeditor/ckeditor_comment.thtml',
    'layout/cms/plugins/ckeditor/ckeditor_contact.thtml',
    'layout/cms/plugins/ckeditor/ckeditor_email.thtml',
    'layout/cms/plugins/ckeditor/ckeditor_sp.thtml',
    'layout/cms/plugins/ckeditor/ckeditor_story.thtml',
    'layout/cms/plugins/ckeditor/ckeditor_submitstory.thtml',
    'layout/cms/plugins/ckeditor/index.html',
    'layout/cms/plugins/ckeditor/mediagallery/index.html',
    'layout/cms/plugins/ckeditor/mediagallery/mb.thtml',
    'layout/cms/plugins/ckeditor/mediagallery/mb_body.thtml',
    'layout/cms/plugins/ckeditor/mediagallery/mb_header.thtml',
    'layout/cms/plugins/filemgmt/filelisting.thtml',
    'layout/cms/plugins/filemgmt/filelisting_category.thtml',
    'layout/cms/plugins/filemgmt/filelisting_record.thtml',
    'layout/cms/plugins/filemgmt/filelisting_subcategory.thtml',
    'layout/cms/plugins/filemgmt/index.html',
    'layout/cms/plugins/filemgmt/sortmenu.thtml',
    'layout/cms/plugins/filemgmt/upload.thtml',
    'layout/cms/plugins/forum/admin/banip_mgmt.thtml',
    'layout/cms/plugins/forum/admin/boards.thtml',
    'layout/cms/plugins/forum/admin/boards_delete.thtml',
    'layout/cms/plugins/forum/admin/boards_edtcategory.thtml',
    'layout/cms/plugins/forum/admin/boards_edtforum.thtml',
    'layout/cms/plugins/forum/admin/index.html',
    'layout/cms/plugins/forum/admin/index.thtml',
    'layout/cms/plugins/forum/admin/ip_records.thtml',
    'layout/cms/plugins/forum/admin/ips_unban.thtml',
    'layout/cms/plugins/forum/admin/migrate_records.thtml',
    'layout/cms/plugins/forum/admin/migratestories.thtml',
    'layout/cms/plugins/forum/admin/mod_add.thtml',
    'layout/cms/plugins/forum/admin/moderators.thtml',
    'layout/cms/plugins/forum/admin/rating.thtml',
    'layout/cms/plugins/forum/alertmsg.thtml',
    'layout/cms/plugins/forum/blocks/block_displayline.thtml',
    'layout/cms/plugins/forum/blocks/centerblock.thtml',
    'layout/cms/plugins/forum/blocks/index.html',
    'layout/cms/plugins/forum/blocks/latestpostsblock.thtml',
    'layout/cms/plugins/forum/footer/footer.thtml',
    'layout/cms/plugins/forum/footer/forum_legend.thtml',
    'layout/cms/plugins/forum/footer/forum_rules.thtml',
    'layout/cms/plugins/forum/footer/forum_time.thtml',
    'layout/cms/plugins/forum/footer/forum_users.thtml',
    'layout/cms/plugins/forum/footer/index.html',
    'layout/cms/plugins/forum/forum_jump.thtml',
    'layout/cms/plugins/forum/forum_search.thtml',
    'layout/cms/plugins/forum/gettopic.thtml',
    'layout/cms/plugins/forum/homepage.thtml',
    'layout/cms/plugins/forum/index.html',
    'layout/cms/plugins/forum/lists.thtml',
    'layout/cms/plugins/forum/mod_confirm.thtml',
    'layout/cms/plugins/forum/navbar.thtml',
    'layout/cms/plugins/forum/pagination.thtml',
    'layout/cms/plugins/forum/posteditor.thtml',
    'layout/cms/plugins/forum/reports/index.html',
    'layout/cms/plugins/forum/reports/notifications.thtml',
    'layout/cms/plugins/forum/search_results.thtml',
    'layout/cms/plugins/forum/signature_profile.thtml',
    'layout/cms/plugins/forum/statusmessage.thtml',
    'layout/cms/plugins/forum/style.css',
    'layout/cms/plugins/forum/topic_full.thtml',
    'layout/cms/plugins/forum/topic_preview.thtml',
    'layout/cms/plugins/forum/topiclisting.thtml',
    'layout/cms/plugins/forum/userprefs/index.html',
    'layout/cms/plugins/forum/userprefs/profile_user_settings.thtml',
    'layout/cms/plugins/links/admin/categoryeditor.thtml',
    'layout/cms/plugins/links/admin/index.html',
    'layout/cms/plugins/links/admin/linkeditor.thtml',
    'layout/cms/plugins/links/categoryactivecol.thtml',
    'layout/cms/plugins/links/categorycol.thtml',
    'layout/cms/plugins/links/categorydropdown.thtml',
    'layout/cms/plugins/links/categorylinks.thtml',
    'layout/cms/plugins/links/categorynavigation.thtml',
    'layout/cms/plugins/links/categoryrow.thtml',
    'layout/cms/plugins/links/index.html',
    'layout/cms/plugins/links/linkdetails.thtml',
    'layout/cms/plugins/links/links.thtml',
    'layout/cms/plugins/links/pagenavigation.thtml',
    'layout/cms/plugins/links/submitlink.thtml',
    'layout/cms/plugins/mediagallery/admin/administration.thtml',
    'layout/cms/plugins/mediagallery/admin/cat_noitems.thtml',
    'layout/cms/plugins/mediagallery/admin/category.thtml',
    'layout/cms/plugins/mediagallery/admin/catitems.thtml',
    'layout/cms/plugins/mediagallery/admin/cfgedit.thtml',
    'layout/cms/plugins/mediagallery/admin/createmembers.thtml',
    'layout/cms/plugins/mediagallery/admin/editalbum_formats.thtml',
    'layout/cms/plugins/mediagallery/admin/editavdefaults.thtml',
    'layout/cms/plugins/mediagallery/admin/editcategory.thtml',
    'layout/cms/plugins/mediagallery/admin/editdefaults.thtml',
    'layout/cms/plugins/mediagallery/admin/editmember.thtml',
    'layout/cms/plugins/mediagallery/admin/exif_tags.thtml',
    'layout/cms/plugins/mediagallery/admin/index.html',
    'layout/cms/plugins/mediagallery/admin/massdelete.thtml',
    'layout/cms/plugins/mediagallery/admin/purgealbums.thtml',
    'layout/cms/plugins/mediagallery/admin/quotaconfirm.thtml',
    'layout/cms/plugins/mediagallery/admin/quotareport.thtml',
    'layout/cms/plugins/mediagallery/admin/rssedit.thtml',
    'layout/cms/plugins/mediagallery/admin/sess_noitems.thtml',
    'layout/cms/plugins/mediagallery/admin/sessions.thtml',
    'layout/cms/plugins/mediagallery/admin/sessitems.thtml',
    'layout/cms/plugins/mediagallery/admin/staticsortalbums.thtml',
    'layout/cms/plugins/mediagallery/admin/staticsortmedia.thtml',
    'layout/cms/plugins/mediagallery/admin/thumbs.thtml',
    'layout/cms/plugins/mediagallery/admin/usage_menu.thtml',
    'layout/cms/plugins/mediagallery/admin/usage_rpt.thtml',
    'layout/cms/plugins/mediagallery/admin/useredit.thtml',
    'layout/cms/plugins/mediagallery/album_page.thtml',
    'layout/cms/plugins/mediagallery/album_page_body_album_cell.thtml',
    'layout/cms/plugins/mediagallery/album_page_body_album_cell_1.thtml',
    'layout/cms/plugins/mediagallery/album_page_body_media_cell.thtml',
    'layout/cms/plugins/mediagallery/album_page_body_media_cell_1.thtml',
    'layout/cms/plugins/mediagallery/album_page_body_media_cell_comment.thtml',
    'layout/cms/plugins/mediagallery/album_page_body_media_cell_keywords.thtml',
    'layout/cms/plugins/mediagallery/album_page_body_media_cell_podcast.thtml',
    'layout/cms/plugins/mediagallery/album_page_noitems.thtml',
    'layout/cms/plugins/mediagallery/albumblock.thtml',
    'layout/cms/plugins/mediagallery/albumrow.thtml',
    'layout/cms/plugins/mediagallery/autotag_ss.thtml',
    'layout/cms/plugins/mediagallery/batch_caption_edit.thtml',
    'layout/cms/plugins/mediagallery/batch_caption_media_items.thtml',
    'layout/cms/plugins/mediagallery/batch_progress.thtml',
    'layout/cms/plugins/mediagallery/cb_featured_album.thtml',
    'layout/cms/plugins/mediagallery/confirm.thtml',
    'layout/cms/plugins/mediagallery/edit_album_permissions.thtml',
    'layout/cms/plugins/mediagallery/editalbum.thtml',
    'layout/cms/plugins/mediagallery/editalbum_admin.thtml',
    'layout/cms/plugins/mediagallery/exif_detail.thtml',
    'layout/cms/plugins/mediagallery/featured_album.thtml',
    'layout/cms/plugins/mediagallery/gallery_page.thtml',
    'layout/cms/plugins/mediagallery/gallery_page_body_1.thtml',
    'layout/cms/plugins/mediagallery/gallery_page_body_3.thtml',
    'layout/cms/plugins/mediagallery/global_album_attr.thtml',
    'layout/cms/plugins/mediagallery/global_album_perm.thtml',
    'layout/cms/plugins/mediagallery/html5upload.thtml',
    'layout/cms/plugins/mediagallery/index-all.thtml',
    'layout/cms/plugins/mediagallery/index.html',
    'layout/cms/plugins/mediagallery/mediablock.thtml',
    'layout/cms/plugins/mediagallery/mediaedit.thtml',
    'layout/cms/plugins/mediagallery/medialink.thtml',
    'layout/cms/plugins/mediagallery/mediarow.thtml',
    'layout/cms/plugins/mediagallery/mp3_podcast.thtml',
    'layout/cms/plugins/mediagallery/mp4.thtml',
    'layout/cms/plugins/mediagallery/profile_userprefs.thtml',
    'layout/cms/plugins/mediagallery/property.thtml',
    'layout/cms/plugins/mediagallery/random_block.thtml',
    'layout/cms/plugins/mediagallery/search.thtml',
    'layout/cms/plugins/mediagallery/search_results2.thtml',
    'layout/cms/plugins/mediagallery/slideshow.thtml',
    'layout/cms/plugins/mediagallery/sortalbum.thtml',
    'layout/cms/plugins/mediagallery/staticsort.thtml',
    'layout/cms/plugins/mediagallery/themes/uikit/album_page.thtml',
    'layout/cms/plugins/mediagallery/themes/uikit/album_page_body_album_cell.thtml',
    'layout/cms/plugins/mediagallery/themes/uikit/album_page_body_media_cell.thtml',
    'layout/cms/plugins/mediagallery/upload.thtml',
    'layout/cms/plugins/mediagallery/userupload.thtml',
    'layout/cms/plugins/mediagallery/view_audio.thtml',
    'layout/cms/plugins/mediagallery/view_flv.thtml',
    'layout/cms/plugins/mediagallery/view_image.thtml',
    'layout/cms/plugins/mediagallery/view_mp4.thtml',
    'layout/cms/plugins/mediagallery/view_video.thtml',
    'layout/cms/plugins/mediagallery/wm_upload.thtml',
    'layout/cms/plugins/mediagallery/wmitems.thtml',
    'layout/cms/plugins/mediagallery/wmmanage.thtml',
    'layout/cms/plugins/pm/compose.thtml',
    'layout/cms/plugins/pm/friends.thtml',
    'layout/cms/plugins/pm/message.thtml',
    'layout/cms/plugins/pm/message_preview.thtml',
    'layout/cms/plugins/pm/pm_box.thtml',
    'layout/cms/plugins/polls/admin/index.html',
    'layout/cms/plugins/polls/admin/pollansweroption.thtml',
    'layout/cms/plugins/polls/admin/polleditor.thtml',
    'layout/cms/plugins/polls/admin/pollquestions.thtml',
    'layout/cms/plugins/polls/index.html',
    'layout/cms/plugins/polls/pollanswer.thtml',
    'layout/cms/plugins/polls/pollblock.thtml',
    'layout/cms/plugins/polls/polllist.thtml',
    'layout/cms/plugins/polls/pollquestion.thtml',
    'layout/cms/plugins/polls/pollquestions.thtml',
    'layout/cms/plugins/polls/pollresult.thtml',
    'layout/cms/plugins/polls/pollvotes_bar.thtml',
    'layout/cms/plugins/staticpages/admin/editor.thtml',
    'layout/cms/plugins/staticpages/admin/index.html',
    'layout/cms/plugins/staticpages/index.html',
    'layout/cms/plugins/staticpages/staticpage.thtml',
    'layout/vintage/admin/block/block_list.thtml',
    'layout/vintage/admin/menu/menulist.thtml',
    'layout/vintage/admin/menu/menutree.thtml',
    'layout/vintage/admin/plugins/plugin_upload_old_confirm.thtml',
    'layout/vintage/admin/user/edituser.thtml',
    'layout/vintage/admin/user/groupedit.thtml',
    'layout/vintage/adminoption.thtml',
    'layout/vintage/adminoption_off.thtml',
    'layout/vintage/menuitem.thtml',
    'layout/vintage/menuitem_last.thtml',
    'layout/vintage/menuitem_none.thtml',
    'layout/vintage/search/headingcolumn.thtml',
    'layout/vintage/search/resultauthdatehits.thtml',
    'layout/vintage/search/resultcolumn.thtml',
    'layout/vintage/search/resultrow.thtml',
    'layout/vintage/search/resultrowenhanced.thtml',
    'layout/vintage/search/resultsummary.thtml',
    'layout/vintage/search/resulttitle.thtml',
    'layout/vintage/search/searchblock.thtml',
    'layout/vintage/search/searchresults.thtml',
    'layout/vintage/search/searchresults_heading.thtml',
    'layout/vintage/search/searchresults_norows.thtml',
    'layout/vintage/search/searchresults_rows.thtml',
    'layout/vintage/stats/singlesummary.thtml',
    'layout/vintage/stats/sitestatistics.thtml',
    'layout/vintage/submit/submitloginrequired.thtml',
    'layout/vintage/useroption.thtml',
    'layout/vintage/useroption_off.thtml',
);

?>