<?php
  /* Contributed by: gallery-addons.com */
$frameData = array(

'name' => 'Scrapbook Shadow Small',

/* Top Left */
'imageTL' => 'TL.gif',
'widthTL' => 12,
'heightTL' => 12,

/* Top */
'imageTTL' => 'TTL.gif',
'widthTTL' => 16,
'heightTTL' => 12,

'imageTT' => 'TT.gif',
'widthTT' => 12,
'heightTT' => 12,

'imageTTR' => 'TTR.gif',
'widthTTR' => 16,
'heightTTR' => 12,

/* Top Right */
'imageTR' => 'TR.gif',
'widthTR' => 12,
'heightTR' => 12,

/* Left */
'imageLLT' => 'LLT.gif',
'widthLLT' => 12,
'heightLLT' => 16,

'imageLL' => 'LL.gif',
'heightLL' => 12,
'widthLL' => 12,

'imageLLB' => 'LLB.gif',
'widthLLB' => 12,
'heightLLB' => 16,


/* Right */
'imageRRT' => 'RRT.gif',
'widthRRT' => 12,
'heightRRT' => 16,


'imageRR' => 'RR.gif',
'widthRR' => 12,
'heightRR' => 12,

'imageRRB' => 'RRB.gif',
'widthRRB' => 12,
'heightRRB' => 16,

/* Bottom Left */
'imageBL' => 'BL.gif',
'widthBL' => 12,
'heightBL' => 12,

/* Bottom */
'imageBBL' => 'BBL.gif',
'widthBBL' => 16,
'heightBBL' => 12,

'imageBB' => 'BB.gif',
'widthBB' => 12,
'heightBB' => 12,

'imageBBR' => 'BBR.gif',
'widthBBR' => 16,
'heightBBR' => 12,

/* Bottom Right */
'imageBR' => 'BR.gif',
'widthBR' => 12,
'heightBR' => 12,

);
?>
