<?php
/* Contributed by: volksport */
$frameData = array(

'name' => 'Diapositive',

/* Top Left */
'imageTL' => 'TL.gif',
'widthTL' => 17,
'heightTL' => 16,

/* Top */
'imageTTL' => '',
'widthTTL' => 0,

'imageTT' => 'TT.gif',
'heightTT' => 16,

'imageTTR' => '',
'widthTTR' => 0,

/* Top Right */
'imageTR' => 'TR.gif',
'widthTR' => 21,
'heightTR' => 16,

/* Left */
'imageLLT' => '',
'heightLLT' => 0,

'imageLL' => 'LL.gif',
'widthLL' => 17,

'imageLLB' => '',
'heightLLB' => 0,

/* Right */
'imageRRT' => '',
'heightRRT' => 0,

'imageRR' => 'RR.gif',
'widthRR' => 21,

'imageRRB' => '',
'heightRRB' => 0,

/* Bottom Left */
'imageBL' => 'BL.gif',
'widthBL' => 17,
'heightBL' => 21,

/* Bottom */
'imageBBL' => '',
'widthBBL' => 0,

'imageBB' => 'BB.gif',
'heightBB' => 21,

'imageBBR' => '',
'widthBBR' => 0,

/* Bottom Right */
'imageBR' => 'BR.gif',
'widthBR' => 21,
'heightBR' => 21

);
?>
