<?php
/**
* glFusion CMS - Media Gallery Plugin
*
* MediaGallery Plugin Table Schema / Default data
*
* @license GNU General Public License version 2 or later
*     http://www.opensource.org/licenses/gpl-license.php
*
*  Copyright (C) 2002-2021 by the following authors:
*   Mark R. Evans   mark AT glfusion DOT org
*
*/

if (!defined ('GVERSION')) {
    die ('This file can not be used on its own.');
}
$_SQL['mg_albums'] = "CREATE TABLE {$_TABLES['mg_albums']} (
  `album_id` int(11) NOT NULL default '0',
  `album_title` varchar(255) NOT NULL default '',
  `album_desc` text NOT NULL,
  `album_parent` int(11) NOT NULL default '0',
  `album_order` int(11) NOT NULL default '0',
  `skin` varchar(255) NOT NULL default 'default',
  `hidden` tinyint(4) NOT NULL default '0',
  `podcast` tinyint(4) NOT NULL default '0',
  `mp3ribbon` tinyint(4) NOT NULL default '0',
  `album_cover` varchar(40) NOT NULL default '-1',
  `album_cover_filename` varchar(255) default '',
  `media_count` int(11) unsigned NOT NULL default '0',
  `album_disk_usage` bigint(20) unsigned NOT NULL default '0',
  `last_update` int(11) NOT NULL default '0',
  `album_views` int(11) NOT NULL default '0',
  `enable_album_views` tinyint(4) NOT NULL default '0',
  `album_view_type` tinyint(4) NOT NULL default '0',
  `image_skin` varchar(255) NOT NULL default 'mgShadow',
  `album_skin` varchar(255) NOT NULL default 'mgAlbum',
  `display_skin` varchar(255) NOT NULL default 'mgShadow',
  `enable_comments` tinyint(4) NOT NULL default '0',
  `exif_display` tinyint(4) NOT NULL default '0',
  `enable_rating` tinyint(4) NOT NULL default '0',
  `va_playback` tinyint(4) NOT NULL default '0',
  `playback_type` tinyint(4) NOT NULL default '0',
  `usealternate` tinyint(4) NOT NULL default '0',
  `tn_attached` tinyint(4) NOT NULL default '0',
  `tnheight` INT NOT NULL DEFAULT '0',
  `tnwidth` INT NOT NULL DEFAULT '0',
  `enable_slideshow` tinyint(4) NOT NULL default '0',
  `enable_random` tinyint(4) NOT NULL default '0',
  `enable_shutterfly` tinyint(4) NOT NULL default '0',
  `auto_rotate` tinyint(4) NOT NULL default '0',
  `enable_views` tinyint(4) NOT NULL default '0',
  `enable_keywords` tinyint(4) NOT NULL default '0',
  `enable_html` tinyint(4) NOT NULL default '0',
  `display_album_desc` tinyint(4) NOT NULL default '0',
  `enable_sort` tinyint(4) NOT NULL default '0',
  `enable_rss` tinyint(4) NOT NULL default '0',
  `enable_postcard` tinyint(4) NOT NULL default '0',
  `albums_first` tinyint(4) NOT NULL default '1',
  `allow_download` tinyint(4) NOT NULL default '0',
  `full_display` tinyint(4) NOT NULL default '0',
  `tn_size` tinyint(4) NOT NULL default '0',
  `max_image_height` int(11) NOT NULL default '0',
  `max_image_width` int(11) NOT NULL default '0',
  `max_filesize` bigint(20) unsigned NOT NULL default '0',
  `display_image_size` tinyint(4) NOT NULL default '2',
  `display_rows` tinyint(4) NOT NULL default '3',
  `display_columns` tinyint(4) NOT NULL default '3',
  `valid_formats` INT( 11 ) UNSIGNED NOT NULL DEFAULT '65535',
  `filename_title` TINYINT( 4 ) NOT NULL DEFAULT '0',
  `shopping_cart` TINYINT( 4 )  NOT NULL DEFAULT '0',
  `rsschildren` TINYINT( 4 ) NOT NULL DEFAULT '0',
  `wm_auto` tinyint(4) NOT NULL default '0',
  `wm_id` int(11) NOT NULL default '0',
  `opacity` int(11) NOT NULL default '0',
  `wm_location` tinyint(4) NOT NULL default '0',
  `album_sort_order` tinyint(4) NOT NULL default '0',
  `member_uploads` tinyint(4) NOT NULL default '0',
  `moderate` tinyint(4) NOT NULL default '0',
  `email_mod` tinyint(4) NOT NULL default '0',
  `featured` tinyint(4) NOT NULL default '0',
  `cbposition` tinyint(1) NOT NULL default '0',
  `cbpage` varchar(20) NOT NULL default '',
  `owner_id` mediumint(9) NOT NULL default '0',
  `group_id` mediumint(9) NOT NULL default '0',
  `mod_group_id` mediumint(9) NOT NULL default '0',
  `perm_owner` tinyint(1) unsigned NOT NULL default '0',
  `perm_group` tinyint(1) unsigned NOT NULL default '0',
  `perm_members` tinyint(1) unsigned NOT NULL default '0',
  `perm_anon` tinyint(1) unsigned NOT NULL default '0',
  PRIMARY KEY  (`album_id`),
  KEY `album_parent` (`album_parent`),
  KEY `last_update` (`last_update`)
) ENGINE=MyISAM
";

$_SQL['mg_config']="CREATE TABLE {$_TABLES['mg_config']} (
  `config_name` varchar(128) NOT NULL default '',
  `config_value` varchar(255) NOT NULL default '',
  PRIMARY KEY  (`config_name`)
) ENGINE=MyISAM
";

$_SQL['mg_media']="CREATE TABLE {$_TABLES['mg_media']} (
  `media_id` varchar(40) NOT NULL default '0',
  `media_filename` varchar(255) NOT NULL default '',
  `media_original_filename` varchar(255) NOT NULL default '',
  `media_mime_ext` varchar(255) NOT NULL default '',
  `media_exif` tinyint(4) NOT NULL default '1',
  `mime_type` varchar(255) NOT NULL default '',
  `media_title` varchar(255) NOT NULL default '',
  `media_desc` text NOT NULL,
  `media_keywords` varchar(255) NOT NULL default '',
  `media_time` int(11) NOT NULL default '0',
  `media_views` int(11) NOT NULL default '0',
  `media_comments` int(11) NOT NULL default '0',
  `media_votes` int(11) NOT NULL default '0',
  `media_rating` decimal(4,2) NOT NULL default '0.00',
  `media_resolution_x` INT(11) NOT NULL default '0',
  `media_resolution_y` int(11) NOT NULL default '0',
  `remote_media` TINYINT(4) NOT NULL default '0',
  `remote_url` TEXT,
  `media_tn_attached` tinyint(4) NOT NULL default '0',
  `media_tn_image` varchar(255) NOT NULL default '',
  `include_ss` tinyint(4) unsigned NOT NULL default '1',
  `media_user_id` mediumint(9) NOT NULL default '0',
  `media_user_ip` varchar(14) NOT NULL default '',
  `media_approval` tinyint(3) NOT NULL default '0',
  `media_type` tinyint(4) NOT NULL default '0',
  `media_upload_time` int(11) NOT NULL default '0',
  `media_category` int(11) NOT NULL default '0',
  `media_watermarked` tinyint(4) NOT NULL default '0',
  `artist` VARCHAR(255) NOT NULL default '',
  `album` VARCHAR(255) NOT NULL default '',
  `genre` VARCHAR(255) NOT NULL default '',
  `v100` tinyint(4) NOT NULL default '0',
  `maint` tinyint(4) NOT NULL default '0',
  PRIMARY KEY  (`media_id`),
  KEY `media_upload_time` (`media_upload_time`)
) ENGINE=MyISAM
";

$_SQL['mg_mediaqueue']="CREATE TABLE {$_TABLES['mg_mediaqueue']} (
  `media_id` varchar(40) NOT NULL default '0',
  `media_filename` varchar(255) NOT NULL default '',
  `media_original_filename` varchar(255) NOT NULL default '',
  `media_mime_ext` varchar(255) NOT NULL default '',
  `media_exif` tinyint(4) NOT NULL default '1',
  `mime_type` varchar(255) NOT NULL default '',
  `media_title` varchar(255) NOT NULL default '',
  `media_desc` text NOT NULL,
  `media_keywords` varchar(255) NOT NULL default '',
  `media_time` int(11) NOT NULL default '0',
  `media_views` int(11) NOT NULL default '0',
  `media_comments` int(11) NOT NULL default '0',
  `media_votes` int(11) NOT NULL default '0',
  `media_rating` decimal(4,2) NOT NULL default '0.00',
  `media_resolution_x` INT(11) NOT NULL default '0',
  `media_resolution_y` int(11) NOT NULL default '0',
  `remote_media` TINYINT(4) NOT NULL default '0',
  `remote_url` TEXT,
  `media_tn_attached` tinyint(4) NOT NULL default '0',
  `media_tn_image` varchar(255) NOT NULL default '',
  `include_ss` tinyint(4) unsigned NOT NULL default '1',
  `media_user_id` mediumint(9) NOT NULL default '0',
  `media_user_ip` varchar(14) NOT NULL default '',
  `media_approval` tinyint(3) NOT NULL default '0',
  `media_type` tinyint(4) NOT NULL default '0',
  `media_upload_time` int(11) NOT NULL default '0',
  `media_category` int(11) NOT NULL default '0',
  `media_watermarked` tinyint(4) NOT NULL default '0',
  `artist` VARCHAR(255) NOT NULL default '',
  `album` VARCHAR(255) NOT NULL default '',
  `genre` VARCHAR(255) NOT NULL default '',
  `v100` tinyint(4) NOT NULL default '0',
  `maint` tinyint(4) NOT NULL default '0',
  PRIMARY KEY  (`media_id`),
  KEY `media_upload_time` (`media_upload_time`)
) ENGINE=MyISAM
";

$_SQL['mg_media_albums']="CREATE TABLE {$_TABLES['mg_media_albums']} (
  `album_id` int(11) NOT NULL default '0',
  `media_id` varchar(40) NOT NULL default '0',
  `media_order` int(11) NOT NULL default '0',
  KEY `media_id` (`media_id`),
  KEY `album_id` (`album_id`)
) ENGINE=MyISAM
";

$_SQL['mg_media_album_queue']="CREATE TABLE {$_TABLES['mg_media_album_queue']} (
  `album_id` int(11) NOT NULL default '0',
  `media_id` varchar(40) NOT NULL default '0',
  `media_order` int(11) NOT NULL default '0',
  KEY `media_id` (`media_id`),
  KEY `album_id` (`album_id`)
) ENGINE=MyISAM
";

$_SQL['mg_playback_options']="CREATE TABLE {$_TABLES['mg_playback_options']} (
  `media_id` varchar(40) NOT NULL default '',
  `option_name` varchar(128) NOT NULL default '',
  `option_value` varchar(255) NOT NULL default '',
  UNIQUE KEY `media_id_2` (`media_id`,`option_name`),
  KEY `media_id` (`media_id`)
) ENGINE=MyISAM
";

$_SQL['mg_usage_tracking']="CREATE TABLE {$_TABLES['mg_usage_tracking']} (
  `time` int(11) NOT NULL default '0',
  `user_id` int(11) NOT NULL default '0',
  `user_name` varchar(127) NOT NULL default '',
  `user_ip` varchar(16) NOT NULL default '',
  `application` varchar(127) NOT NULL default '',
  `album_title` varchar(127) NOT NULL default '',
  `media_title` varchar(127) NOT NULL default '',
  `media_id` varchar(40) NOT NULL default '0',
  KEY `time` (`time`)
) ENGINE=MyISAM
";

$_SQL['mg_userprefs']="CREATE TABLE {$_TABLES['mg_userprefs']} (
  `uid` mediumint(8) NOT NULL default '0',
  `active` tinyint(4) NOT NULL default '1',
  `display_rows` tinyint(4) NOT NULL default '0',
  `display_columns` tinyint(4) NOT NULL default '0',
  `mp3_player` tinyint(4) NOT NULL default '-1',
  `playback_mode` tinyint(4) NOT NULL default '-1',
  `tn_size` tinyint(4) NOT NULL default '1',
  `quota` bigint(20) unsigned NOT NULL default '0',
  `member_gallery` mediumint(8) NOT NULL default '0',
  PRIMARY KEY  (`uid`)
) ENGINE=MyISAM
";

$_SQL['mg_watermarks']="CREATE TABLE {$_TABLES['mg_watermarks']} (
  `wm_id` int(11) NOT NULL default 0,
  `owner_id` int(11) NOT NULL default '0',
  `filename` varchar(255) NOT NULL default '',
  `description` varchar(255) NOT NULL default '',
  PRIMARY KEY  (`wm_id`)
) ENGINE=MyISAM
";



$_SQL['mg_session_items'] = "CREATE TABLE {$_TABLES['mg_session_items']} (
  `id` bigint(20) unsigned NOT NULL auto_increment,
  `session_id` varchar(40) NOT NULL default '',
  `mid` varchar(40) NOT NULL default '',
  `aid` int(11) NOT NULL default '0',
  `data` varchar(255) NOT NULL default '',
  `data2` varchar(255) NOT NULL default '',
  `data3` varchar(255) NOT NULL default '',
  `status` tinyint(4) NOT NULL default '0',
  PRIMARY KEY  (`id`),
  KEY `session_id` (`session_id`)
) ENGINE=MyISAM
";

$_SQL['mg_session_items2'] = "CREATE TABLE {$_TABLES['mg_session_items2']} (
  `id` bigint(20) NOT NULL,
  `data1` varchar(255) NOT NULL,
  `data2` varchar(255) NOT NULL,
  `data3` varchar(255) NOT NULL,
  `data4` varchar(255) NOT NULL,
  `data5` varchar(255) NOT NULL,
  `data6` varchar(255) NOT NULL,
  `data7` varchar(255) NOT NULL,
  `data8` varchar(255) NOT NULL,
  `data9` varchar(255) NOT NULL,
  KEY `id` (`id`)
) ENGINE=MyISAM
";

$_SQL['mg_session_log'] = "CREATE TABLE {$_TABLES['mg_session_log']} (
  `session_id` varchar(40) NOT NULL default '',
  `session_log` varchar(255) NOT NULL default '',
  KEY `session_id` (`session_id`)
) ENGINE=MyISAM
";

$_SQL['mg_sessions'] = "CREATE TABLE {$_TABLES['mg_sessions']} (
  `session_id` varchar(40) NOT NULL default '',
  `session_uid` mediumint(8) NOT NULL default '0',
  `session_description` varchar(255) NOT NULL default '',
  `session_status` tinyint(4) NOT NULL default '0',
  `session_cycles` tinyint(4) NOT NULL default '0',
  `session_action` varchar(255) NOT NULL default '',
  `session_origin` varchar(255) NOT NULL default '',
  `session_start_time` bigint(11) NOT NULL default '0',
  `session_end_time` bigint(11) NOT NULL default '0',
  `session_var0` varchar(255) default NULL,
  `session_var1` varchar(255) default NULL,
  `session_var2` varchar(255) default NULL,
  `session_var3` varchar(255) default NULL,
  `session_var4` varchar(255) default NULL,
  PRIMARY KEY  (`session_id`)
) ENGINE=MyISAM
";

$_SQL['mg_category'] = "CREATE TABLE {$_TABLES['mg_category']} (
  `cat_id` mediumint(9) NOT NULL default '0',
  `cat_name` varchar(255) NOT NULL default '',
  `cat_description` varchar(255) NOT NULL default '',
  `cat_order` mediumint(11) NOT NULL default '0',
  PRIMARY KEY  (`cat_id`)
) ENGINE=MyISAM
";

$_SQL['mg_sort'] = "CREATE TABLE {$_TABLES['mg_sort']} (
  `sort_id` varchar(40) NOT NULL default '',
  `sort_user` varchar(40) NOT NULL default '',
  `sort_query` text NOT NULL,
  `sort_results` int(11) NOT NULL default '0',
  `sort_datetime` int(11) NOT NULL default '0',
  `referer` varchar(255) NOT NULL default '',
  `keywords` varchar(255) NOT NULL default ''
) ENGINE=MyISAM
";

$_SQL['mg_postcard'] = "CREATE TABLE {$_TABLES['mg_postcard']} (
  `pc_id` varchar(40) NOT NULL default '',
  `mid` varchar(40) NOT NULL default '',
  `to_name` varchar(255) NOT NULL default '',
  `to_email` varchar(255) NOT NULL default '',
  `from_name` varchar(255) NOT NULL default '',
  `from_email` varchar(255) NOT NULL default '',
  `subject` varchar(255) NOT NULL default '',
  `message` text NOT NULL,
  `pc_time` int(11) NOT NULL default '0',
  `uid` mediumint(9) NOT NULL default '0',
   PRIMARY KEY  (`pc_id`)
) ENGINE=MyISAM
";

$_SQL['mg_rating'] = "CREATE TABLE {$_TABLES['mg_rating']} (
  `id` int(11) unsigned NOT NULL default '0',
  `ip_address` varchar(14) NOT NULL,
  `uid` mediumint(8) NOT NULL,
  `media_id` varchar(40) NOT NULL,
  `ratingdate` int(11) NOT NULL,
  `owner_id` mediumint(8) NOT NULL default '2',
  PRIMARY KEY  (`id`),
  KEY `owner_id` (`owner_id`)
) ENGINE=MyISAM
";

$_SQL['mg_exif_tags']="CREATE TABLE {$_TABLES['mg_exif_tags']} (
  `name` varchar(128) NOT NULL default '',
  `selected` tinyint(1) NOT NULL default '0',
  PRIMARY KEY  (`name`)
) ENGINE=MyISAM
";

$_SQL['mg_watermark_data']="INSERT INTO {$_TABLES['mg_watermarks']} VALUES (0, 0, 'blank.png', '---');";

$_SQL['exif_tag_data']="INSERT INTO {$_TABLES['mg_exif_tags']} (`name`, `selected`) VALUES ('ApertureValue', 1),
('ShutterSpeedValue', 1),
('ISO', 1),
('FocalLength', 0),
('Flash', 1),
('ACDComment', 0),
('AEWarning', 0),
('AFFocusPosition', 0),
('AFPointSelected', 0),
('AFPointUsed', 0),
('Adapter', 0),
('Artist', 0),
('BatteryLevel', 0),
('BitsPerSample', 0),
('BlurWarning', 0),
('BrightnessValue', 0),
('CCDSensitivity', 0),
('CameraID', 0),
('CameraSerialNumber', 0),
('Color', 0),
('ColorMode', 0),
('ColorSpace', 0),
('ComponentsConfiguration', 0),
('CompressedBitsPerPixel', 0),
('Compression', 0),
('ContinuousTakingBracket', 0),
('Contrast', 0),
('Converter', 0),
('Copyright', 0),
('CustomFunctions', 0),
('CustomerRender', 0),
('DateTime', 1),
('DigitalZoom', 0),
('DigitalZoomRatio', 0),
('DriveMode', 0),
('EasyShooting', 0),
('ExposureBiasValue', 0),
('ExposureIndex', 0),
('ExposureMode', 0),
('ExposureProgram', 0),
('FileSource', 0),
('FirmwareVersion', 0),
('FlashBias', 0),
('FlashDetails', 0),
('FlashEnergy', 0),
('FlashMode', 0),
('FlashPixVersion', 0),
('FlashSetting', 0),
('FlashStrength', 0),
('FocalPlaneResolutionUnit', 0),
('FocalPlaneXResolution', 0),
('FocalPlaneYResolution', 0),
('FocalUnits', 0),
('Focus', 0),
('FocusMode', 0),
('FocusWarning', 0),
('GainControl', 0),
('ImageAdjustment', 0),
('ImageDescription', 0),
('ImageHistory', 0),
('ImageLength', 0),
('ImageNumber', 0),
('ImageSharpening', 0),
('ImageSize', 0),
('ImageType', 0),
('ImageWidth', 0),
('InterColorProfile', 0),
('Interlace', 0),
('InteroperabilityIFD.InteroperabilityIndex', 0),
('InteroperabilityIFD.InteroperabilityVersion', 0),
('InteroperabilityIFD.RelatedImageFileFormat', 0),
('InteroperabilityIFD.RelatedImageLength', 0),
('InteroperabilityIFD.RelatedImageWidth', 0),
('JPEGTables', 0),
('JpegIFByteCount', 0),
('JpegIFOffset', 0),
('JpegQual', 0),
('LightSource', 0),
('LongFocalLength', 0),
('Macro', 0),
('Make', 1),
('ManualFocusDistance', 0),
('MaxApertureValue', 0),
('MeteringMode', 0),
('Model', 1),
('Noise', 0),
('NoiseReduction', 0),
('Orientation', 0),
('OwnerName', 0),
('PhotometricInterpret', 0),
('PhotoshopSettings', 0),
('PictInfo', 0),
('PictureMode', 0),
('PlanarConfiguration', 0),
('Predictor', 0),
('PrimaryChromaticities', 0),
('Quality', 0),
('ReferenceBlackWhite', 0),
('RelatedSoundFile', 0),
('ResolutionUnit', 0),
('RowsPerStrip', 0),
('SamplesPerPixel', 0),
('Saturation', 0),
('SceneCaptureMode', 0),
('SceneType', 0),
('SecurityClassification', 0),
('SelfTimer', 0),
('SelfTimerMode', 0),
('SensingMethod', 0),
('SequenceNumber', 0),
('Sharpness', 0),
('ShortFocalLength', 0),
('SlowSync', 0),
('Software', 0),
('SoftwareRelease', 0),
('SpatialFrequencyResponse', 0),
('SpecialMode', 0),
('SpectralSensitivity', 0),
('StripByteCounts', 0),
('StripOffsets', 0),
('SubIFDs', 0),
('SubfileType', 0),
('SubjectDistance', 0),
('SubjectLocation', 0),
('SubsecTime', 0),
('SubsecTimeDigitized', 0),
('SubsecTimeOriginal', 0),
('TIFF/EPStandardID', 0),
('TileByteCounts', 0),
('TileLength', 0),
('TileOffsets', 0),
('TileWidth', 0),
('TimeZoneOffset', 0),
('Tone', 0),
('TransferFunction', 0),
('UserComment', 0),
('Version', 0),
('WhiteBalance', 0),
('WhitePoint', 0),
('YCbCrCoefficients', 0),
('YCbCrPositioning', 0),
('YCbCrSubSampling', 0),
('xResolution', 0),
('yResolution', 0),
('ExifImageHeight', 0),
('ExifImageWidth', 0),
('IPTC/SupplementalCategories', 0),
('IPTC/Keywords', 0),
('IPTC/Caption', 0),
('IPTC/CaptionWriter', 0),
('IPTC/Headline', 0),
('IPTC/SpecialInstructions', 0),
('IPTC/Category', 0),
('IPTC/Byline', 0),
('IPTC/BylineTitle', 0),
('IPTC/Credit', 0),
('IPTC/Source', 0),
('IPTC/CopyrightNotice', 0),
('IPTC/ObjectName', 0),
('IPTC/City', 0),
('IPTC/ProvinceState', 0),
('IPTC/CountryName', 0),
('IPTC/OriginalTransmissionReference', 0),
('IPTC/DateCreated', 0),
('IPTC/CopyrightFlag', 0),
('IPTC/TimeCreated', 0);";

$_SQL['config_data_1']="INSERT INTO {$_TABLES['mg_config']} (`config_name`, `config_value`) VALUES
('path_mediaobjects',''),
('mediaobjects_url',''),
('path_mg','mediagallery'),
('menulabel', 'Media Gallery');";

$_SQL['config_data_2']="INSERT INTO {$_TABLES['mg_config']} (`config_name`, `config_value`) VALUES
('display_rows', '3'),
('album_display_columns', '1'),
('album_display_rows', '9'),
('display_columns', '3'),
('loginrequired', '0'),
('graphicspackage', '2'),
('graphicspackage_path', '/usr/local/bin/'),
('displayblocks', '0'),
('usage_tracking', '0'),
('dfid', '0'),
('htmlallowed', '0'),
('whatsnew', '1'),
('truncate_breadcrumb', '0'),
('jpg_orig_quality', '85'),
('jpg_quality', '85'),
('whatsnew_time', '7'),
('gallery_tn_size', '4'),
('gallery_tn_height', '250'),
('gallery_tn_width', '250'),
('mp3_player', '0'),
('seperator', '::'),
('up_display_rows_enabled', '1'),
('up_display_columns_enabled', '1'),
('up_mp3_player_enabled', '1'),
('up_av_playback_enabled', '1'),
('up_thumbnail_size_enabled', '1'),
('tn_jpg_quality', '85'),
('ftp_path', ''),
('tmp_path', ''),
('preserve_filename', '1'),
('discard_original', '0'),
('verbose', '0'),
('disable_whatsnew_comments', '1'),
('enable_media_id', '1'),
('full_in_popup', '0'),
('commentbar', '1'),
('title_length', '28'),
('profile_hook', '1'),
('indexskin', 'mgAlbum'),
('ad_podcast', '0'),
('ad_enable_comments', '1'),
('ad_exif_display', '0'),
('ad_enable_rating', '1'),
('ad_playback_type', '2'),
('ad_enable_slideshow', '1'),
('ad_enable_random', '1'),
('ad_enable_shutterfly', '1'),
('ad_enable_views', '1'),
('ad_enable_keywords', '1'),
('ad_display_album_desc', '0'),
('ad_enable_album_views', '1'),
('ad_enable_sort', '1'),
('ad_enable_rss', '0'),
('ad_enable_postcard', '1'),
('ad_albums_first', '1'),
('ad_full_display', '0'),
('ad_tn_size', '4'),
('ad_tn_height', '200'),
('ad_tn_width', '200'),
('ad_display_rows', '4'),
('ad_display_columns', '3'),
('ad_member_uploads', '0'),
('ad_moderate', '0'),
('ad_email_mod', '0'),
('ad_wm_auto', '0'),
('ad_wm_id', '0'),
('ad_wm_opacity', '10'),
('ad_wm_location', '1'),
('ad_album_sort_order', '0'),
('ad_max_filesize', '0'),
('ad_max_image_height', '0'),
('ad_max_image_width', '0'),
('ad_display_image_size', '8'),
('ad_perm_owner', '3'),
('ad_perm_group', '3'),
('ad_perm_members', '2'),
('ad_perm_anon', '2'),
('ad_allow_download', '0'),
('ad_valid_formats', '983039'),
('ad_filename_title', '0'),
('ad_image_skin', 'mgShadow'),
('ad_album_skin', 'mgAlbum'),
('ad_display_skin', 'mgShadow'),
('ad_skin', 'default'),
('ad_mp3ribbon', '0'),
('ad_rsschildren', '1'),
('custom_image_height', '2048'),
('custom_image_width', '2048'),
('random_width', '120'),
('def_refresh_rate', '30'),
('def_time_limit', '90'),
('def_item_limit', '10'),
('asf_autostart', '1'),
('asf_enablecontextmenu', '1'),
('asf_stretchtofit', '1'),
('asf_showstatusbar', '1'),
('asf_uimode', 'full'),
('asf_playcount', '9999'),
('asf_height', '480'),
('asf_width', '640'),
('asf_bgcolor', '#FFFFFF'),
('mov_autoref', '1'),
('mov_autoplay', '1'),
('mov_controller', '1'),
('mov_kioskmode', '1'),
('mov_scale', 'tofit'),
('mov_loop', '0'),
('mov_height', '480'),
('mov_width', '640'),
('mov_bgcolor', '#FFFFFF'),
('mp3_autostart', '1'),
('mp3_enablecontextmenu', '1'),
('mp3_showstatusbar', '1'),
('mp3_loop', '0'),
('mp3_uimode', '0'),
('swf_play', '1'),
('swf_menu', '0'),
('swf_loop', '0'),
('swf_quality', 'high'),
('swf_scale', 'showall'),
('swf_wmode', 'transparent'),
('swf_flashvars', ''),
('swf_version', '6'),
('swf_height', '480'),
('swf_width', '640'),
('swf_bgcolor', '#FFFFFF'),
('swf_allowscriptaccess', 'sameDomain'),
('rss_full_enabled', '1'),
('rss_feed_type', 'RSS2.0'),
('rss_ignore_empty', '1'),
('rss_anonymous_only', '1'),
('rss_feed_name', 'mgmedia'),
('postcard_retention', '7'),
('subalbum_select', '1'),
('member_albums', '0'),
('member_quota', '0'),
('member_auto_create', '0'),
('member_create_new', '0'),
('member_album_root', '0'),
('member_album_archive', '0'),
('member_enable_random', '1'),
('member_max_width', '0'),
('member_max_height', '0'),
('member_max_filesize', '0'),
('member_uploads', '0'),
('member_moderate', '0'),
('member_email_mod', '0'),
('member_perm_owner', '3'),
('member_perm_group', '3'),
('member_perm_members', '0'),
('member_perm_anon', '0'),
('member_valid_formats', '65535'),
('last_usage_purge', '0'),
('random_skin', 'mgShadow'),
('at_border', '1'),
('at_align', 'auto'),
('at_width', '0'),
('at_height', '0'),
('at_src', 'tn'),
('at_autoplay', '0'),
('at_enable_link', '1'),
('at_delay', '5'),
('at_showtitle', '0'),
('use_flowplayer', '0'),
('search_columns', '3'),
('search_rows', '4'),
('search_playback_type', '0'),
('search_enable_views', '1'),
('search_enable_rating', '1'),
('gallery_only', '0'),
('ad_mod_id', '19'),
('ad_mod_group_id', '19'),
('member_mod_group_id', '19');
";
?>